### ISSUE TITLE
Cleanup old files

### ISSUE THREAD

**Issue by emackey** [moneimne/WebGL-PBR#3]
Hi @moneimne, this is a great little PBR demo you have here.  @pjcozzi asked me if I could do a bit of code review on it, with a particular focus on JavaScript and code-organization concerns.

I'm just going to open some GitHub issues on random stuff I find.  Some may be my own misunderstanding that can be closed, some could be left open to address in the future, some might be short-term fixes, etc.

This first issue addresses some duplication of files, particularly `scene.js` vs. `scene2.js`, and `pbr-frag.glsl` vs. `single-light-pbr-frag.glsl`.  It looks like sometimes these files get copied, perhaps just to preserve old versions for reference.

Since we're in git source control, of course there is no need to keep old versions laying around in the `master` branch.  Git offers ample tools to retrieve or compare history, or of course you can keep alternate or experimental copies of things around in other branches if needed.  Keeping the head of `master` free of such things will make the repo much more welcoming to people looking for a reference implementation.

**Comment by moneimne** [comment]
Thanks, @emackey! I really appreciate all the help. I'll make sure to address any issues you mention.

As for this one, I agree that there were repetitive files that could be confusing, so I just removed them.

**Comment by emackey** [comment]
Fixed in 75199d76.
