### ISSUE TITLE
Don't show user-level errors on web developer console

### ISSUE THREAD

**Issue by emackey** [moneimne/WebGL-PBR#5]
There are some `console.log` messages for things like `Failed to get the rendering context for WebGL`.

Although this is a reference app specifically for web developers, ideally these messages would still get shown to the user, because new developers are coming in initially as users of the reference app.

Probably there should be some `<div id="error"></div>` or similar that could be written to from JavaScript and would show the error message in red on the screen.

**Comment by moneimne** [comment]
Fixed in 2c815bf.
