### ISSUE TITLE
Reference shader

### ISSUE THREAD

**Issue by emackey** [moneimne/WebGL-PBR#8]
So @moneimne got this project off to an awesome start, and then @snagy has made a fork with a number of substantial improvements to the shaders (and his fork has some JS cleanup from me).

What's the plan from here?  Should there be a PR to bring @snagy's changes back to this repo?  @snagy are you done making changes, or is there more to do?  Can we compile a list of remaining TODO items, possibly just using the GitHub issue tracker here?

It would be great for this to become the official glTF 2.0 "reference shader" implementation.  Should that implementation officially live in this repo, or @snagy's repo, or even a Khronos repo?

Any thoughts or clarifications of the intended direction here would be appreciated.  Thanks!

/cc @pjcozzi

**Comment by pjcozzi** [comment]
> Should there be a PR to bring @snagy's changes back to this repo?

I believe that is the plan.  CC @snagy @sbtron

> It would be great for this to become the official glTF 2.0 "reference shader" implementation. Should that implementation officially live in this repo, or @snagy's repo, or even a Khronos repo?

Being the reference implementation has always been the plan.  Moving to a Khronos repo is OK with me if @moneimne agrees.  It would get more attention there.

**Comment by moneimne** [comment]
> Moving to a Khronos repo is OK with me if @moneimne agrees.

Yes, of course!

**Comment by pjcozzi** [comment]
Great, @emackey and @outofcontrol will help do the transfer.  We'd like to do it _soon_ so we can reference the new url.  Just after @snagy's changes are merged.

**Comment by allcreatures** [comment]
We can transfer the repository to KhronosGroup/WebGL-PBR. Given the permissions on the Khronos Organization, if I can get permission to access the settings on moneimne/WebGL-PBR, it would make the move quite simple. Let me know once the final merges are done and permissions have been changed and I'll do the move.

**Comment by pjcozzi** [comment]
Can we also rename to glTF-WebGL-PBR?

**Comment by sbtron** [comment]
+1  glTF-WebGL-PBR 
can we also add a ghpage for it so demo is viewable

**Comment by emackey** [comment]
>  if I can get permission to access the settings on moneimne/WebGL-PBR

@outofcontrol Do you happen to know how one grants such permission?  We figured out how to grant push access, but that doesn't grant settings access.

> can we also add a ghpage for it so demo is viewable

@sbtron Yes, this repo is already usable by GitHub Pages directly from the master branch, and I have my own fork published as such.  Currently there is bad-to-terrible network performance due to issue #9 which I need to carve out some time to fix very soon.  Other than that it's as simple as enabling Pages on master.

**Comment by emackey** [comment]
@outofcontrol Another option, given the proposed rename, is you could create a blank repo with the new name `glTF-WebGL-PBR` and grant push access to myself, @snagy, and @moneimne.  There are a few issues in the existing repo, mostly mine, that I could close or copy over manually to the new repo.

**Comment by allcreatures** [comment]
Repo create. Invite sent. Once you accept I will move you up to have the access you need.

**Comment by emackey** [comment]
@outofcontrol Awesome, thanks.  I didn't see the invite come through yet, can you send a new one to me at @emackey?

Also, let's drop "Senior Design Project" from the tagline, as this has moved beyond that now.

**Comment by emackey** [comment]
Got the invite, thanks!

**Comment by emackey** [comment]
Hi folks!  The new repo is now populated:

https://github.com/KhronosGroup/glTF-WebGL-PBR

And a new live (ghpages) demo is up and running now thanks to @outofcontrol :

http://github.khronos.org/glTF-WebGL-PBR/

**Comment by emackey** [comment]
@snagy since we created a new repo with a new name, GitHub likely won't allow you to create PRs from your existing fork into the new Khronos repo, even though it's the same git tree.  You could (a) create a new fork from the new repo, and create PRs from there, or (b) ask James to grant you push access to the new repo, so you can push branches directly there and create PRs that way.

**Comment by pjcozzi** [comment]
@moneimne could you please update this repo to just contain a README.md that points to the new repo?

**Comment by moneimne** [comment]
> update this repo to just contain a README.md that points to the new repo

Done!

**Comment by pjcozzi** [comment]
Thanks @moneimne!

Last request - can you please review the 3 issues in this repo, close them, and then open new issues (linking to the old ones) in the repo new for issues that are still relevant?

**Comment by emackey** [comment]
This issue is done and can be closed.  Now only #1 remains.
